### ISSUE TITLE
Change File Browser

### ISSUE THREAD

**Issue by larsiusprime** [HaxeFlixel/flixel-editors#1]
Right now I'm using systools, which isn't all that stable and is kind of clunky, even though it uses native OS file browsers.

I think I want to try out haxeui's file dialogs:
https://github.com/ianharrigan/haxeui-file-dialogs

**Comment by Gama11** [comment]
Tbh, I would prefer native file dialogs - just not the ones that are used right now, on at least windows it's some sort of minimalist, trimmed down version.

**Comment by larsiusprime** [comment]
It's the "browse for folder" dialog, rather than the "browse for file" dialog. One of the main issues is that it crashes unexpectedly, but I'll see what I can do.

**Comment by larsiusprime** [comment]
Well, I fixed the crashing issues. I'll call this good for now until I have a better idea.
